yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from posts.views import (CommentCreate, FollowIndex, GroupPostView, IndexView,
                         PostCreate, PostDelete, PostDetailView, PostEdit,
                         ProfileDetailView, ProfileFollow, ProfileUnfollow)

app_name = 'posts'

urlpatterns = [
    path('', IndexView.as_view(), name='main'),
    path('group/<slug:slug>/', GroupPostView.as_view(), name='group_list'),
    path(
        'profile/<str:username>/',
        ProfileDetailView.as_view(),
        name='profile'),
    path('posts/<int:post_id>/', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('posts/<int:post_id>/edit/', PostEdit.as_view(), name='post_edit'),
    path(
        'posts/<int:post_id>/delete/',
        PostDelete.as_view(),
        name='post_delete'),
    path(
        'posts/<int:post_id>/comment/',
        CommentCreate.as_view(),
        name='add_comment'),
    path('follow/', FollowIndex.as_view(), name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        ProfileFollow.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        ProfileUnfollow.as_view(),
        name='profile_unfollow'
    ),
]

yatube/search/urls.py
# search/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.search, name='search'),
]

yatube/users/urls.py
# users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change_form',),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done',),
    path(
        'password_reset_form/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form',),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('search/', include('search.urls', namespace='search')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/search/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string

from posts.models import Post


def search(request):
    # This realis AJAX jqury
    # if request.is_ajax() and request.GET['data']:
    #     content = {'search_list': Post.objects.filter(
    #         text__icontains=request.GET['data']),}
    # result = render_to_string('includes/search.html', context=content)

    content = {'search_list': ''}
    data_search = request.GET['data'] or None

    if data_search:
        content = {'search_list': Post.objects.filter(
            text__icontains=data_search)}
    result = render_to_string('includes/search.html', context=content)
    return JsonResponse({'result': result})

yatube/templates/includes/add_comment.html
{% if user.is_authenticated %}
<div class="card my-4">
  <h5 class="card-header">Добавить комментарий:</h5>
  <div class="card-body">

    <form method="post" action="{% url 'posts:add_comment' post.id %}">
      {% csrf_token %}

        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-danger">{{ message }}</div>
          {% endfor %}
        {% endif %}

      {% include 'includes/view_form.html' %}

      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Отправить
        </button>
      </div>
    </form>
  </div>
</div>
{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}

<header>
  <nav 
  class="navbar navbar-expand-lg navbar-light" 
  style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:main' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>

      <form class="d-flex justify-content-start">
        <input class="form-control me-2 search-input" type="search" placeholder="Поиск поста" aria-label="Search">
        {{ search_list }}
        <div id="search-drop-block" class="dropdown-menu search-result-block bg-light"></div>
      </form>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="nav nav-pills flex-lg-row flex-md-column flex-sm-column">
          {% with request.resolver_match.view_name as view_name %}
            <li class="nav-item"> 
              <a 
                class="nav-link 
                  {% if view_name  == 'about:author' %}
                    active 
                  {% endif %}" 
                href="{% url 'about:author' %}">
                  Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a 
                class="nav-link
                  {% if view_name  == 'about:tech' %}
                    active 
                  {% endif %}"  
                href="{% url 'about:tech' %}">
                  Технологии
              </a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item"> 
                <a 
                  class="nav-link
                  {% if view_name  == 'posts:post_create' %}
                    active 
                  {% endif %}" 
                  href="{% url 'posts:post_create' %}">
                    Новая запись
                </a>
              </li>
              <li class="nav-item"> 
                <a 
                  class="nav-link link-light
                    {% if view_name  == 'users:password_change_form' %}
                      active 
                    {% endif %}" 
                  href="{% url 'users:password_change_form' %}">
                    Изменить пароль
                </a>
              </li>
              <li class="nav-item"> 
                <a 
                  class="nav-link link-light" 
                  href="{% url 'users:logout' %}">
                    Выйти
                </a>
              </li>
              <li class="nav-item">
                <a 
                  class="nav-link link-light" 
                  href="#">
                  Пользователь: {{ user.username }} 
                </a>   
              <li>
            {% else %}
            <li class="nav-item"> 
              <a 
                class="nav-link link-light
                  {% if view_name  == 'users:login' %}
                    active 
                  {% endif %}" 
                href="{% url 'users:login' %}">
                  Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a 
                class="nav-link link-light
                {% if view_name  == 'users:signup' %}
                  active 
                {% endif %}" 
                href="{% url 'users:signup' %}">
                  Регистрация
              </a>
            </li>
            {% endif %}
          {% endwith %}
        </ul>
      </div>
    </div>
  </nav>
</header>

yatube/templates/includes/search.html
{% if search_list %}
<span class="dropdown-item-text">Найдено постов: <b>{{ search_list.count }}</b></span>
<br>
    {% for object in search_list %}
    
        <a class="dropdown-item search-link-post"  href="{% url 'posts:post_detail' object.id %}">
            <span><b>{{ forloop.counter }}.</b></span>
            <span class="search-item-name">{{ object.text|truncatechars:30 }}</span>
        </a>

    {% endfor %}
{% else %}
    <p>Посты не найдены</p>
{% endif %}

yatube/templates/includes/view_comment.html
<div class="media mb-4">
  <div class="media-body">
    {% for comment in comments %}
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author %}">
          {{ comment.author }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
      <p>
        Дата: {{ comment.created }}
      </p>
      {% if not forloop.last %}
        <hr />
      {% endif %}
    {% endfor %}
  </div>
</div>

yatube/templates/includes/view_errors.html
{% load user_filters %} 

{% if form.errors %}
  {% for field in form %} 
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endif %}

yatube/templates/includes/view_form.html
{% load user_filters %}

{% for field in form %}
  <div class="form-group row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
  </div>
{% endfor %}