yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from posts.views import (CommentCreate, FollowIndex, GroupPostView, IndexView,
                         PostCreate, PostDelete, PostDetailView, PostEdit,
                         ProfileDetailView, ProfileFollow, ProfileUnfollow)

app_name = 'posts'

urlpatterns = [
    path('', IndexView.as_view(), name='main'),
    path('group/<slug:slug>/', GroupPostView.as_view(), name='group_list'),
    path(
        'profile/<str:username>/',
        ProfileDetailView.as_view(),
        name='profile'),
    path('posts/<int:post_id>/', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('posts/<int:post_id>/edit/', PostEdit.as_view(), name='post_edit'),
    path(
        'posts/<int:post_id>/delete/',
        PostDelete.as_view(),
        name='post_delete'),
    path(
        'posts/<int:post_id>/comment/',
        CommentCreate.as_view(),
        name='add_comment'),
    path('follow/', FollowIndex.as_view(), name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        ProfileFollow.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        ProfileUnfollow.as_view(),
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('search/', include('search.urls', namespace='search')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from core.models import CreatedModel

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста')
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def get_absolute_url(self):
        return reverse('posts:profile', args=[self.author.username])

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()

    class Meta:
        verbose_name = 'Группы'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            new_slug = self.title.translate(
                str.maketrans(
                    "абвгдеёжзийклмнопрстуфхцчшщъыьэюя\
                        +АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
                    "abvgdeejzijklmnoprstufhzcss_y_eua\
                        +ABVGDEEJZIJKLMNOPRSTUFHZCSS_Y_EUA"
                )
            )
            self.slug = slugify(new_slug)[:200]
        if Group.objects.filter(slug=self.slug).exists():
            raise ValidationError(
                f'Адрес "{self.slug}" уже существует, '
                'придумайте уникальное значение'
            )
        super().save(*args, **kwargs)


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comment',
        verbose_name='Коментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comment',
        verbose_name='Автор'
    )
    text = models.TextField(
        'Текст',
        help_text='Текст нового комментария'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def get_absolute_url(self):
        return reverse('posts:post_detail', args=[self.post.id])

    def __str__(self):
        return self.text


class Follow(CreatedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписчики'
        verbose_name_plural = 'Подписчики'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_bundle_user_author'
            )
        ]

    def get_absolute_url(self):
        return reverse('posts:follow_index')

yatube/posts/forms.py
from django.forms import ModelForm

from posts.models import Comment, Post


class PostForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['group'].empty_label = 'Категория не выбрана'

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

        help_texts = {
            'group': 'Группа, к которой будет относиться пост',
            'text': 'Текст нового поста',
        }
        labels = {
            'text': 'Текст поста',
            'group': 'Выбор группы',
        }


class CommentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].empty_label = 'Комментарий не должен быть пустым'

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_list_or_404, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from posts.forms import CommentForm, PostForm
from posts.models import Follow, Post
from yatube.settings import COUNT_PAGINATOR_PAGE

User = get_user_model()


class IndexView(ListView):
    model = Post
    template_name = 'posts/index.html'
    paginate_by = COUNT_PAGINATOR_PAGE


class GroupPostView(ListView):
    model = Post
    template_name = 'posts/group_list.html'
    paginate_by = COUNT_PAGINATOR_PAGE

    def get_queryset(self):
        return get_list_or_404(Post, group__slug=self.kwargs['slug'])


class ProfileDetailView(ListView):
    model = Post
    paginate_by = COUNT_PAGINATOR_PAGE
    template_name = 'posts/profile.html'

    def get_queryset(self):
        return (
            Post.objects.select_related('author')
            .filter(author__username=self.kwargs['username'])
        )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["author"] = get_object_or_404(
            User, username=self.kwargs['username']
        )
        if (
            Follow.objects.filter(
                user__username=self.request.user,
                author__username=self.kwargs['username']).exists()
        ):
            context["following"] = True
        return context


class PostDetailView(CreateView):
    form_class = CommentForm
    template_name = 'posts/post_detail.html'
    pk_url_kwarg = 'post_id'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = get_object_or_404(Post, pk=self.kwargs['post_id'])
        context["comments"] = context["post"].comment.all()
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    form_class = PostForm
    template_name = 'posts/create_post.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_edit"] = False
        return context


class PostEdit(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    pk_url_kwarg = 'post_id'
    template_name = 'posts/create_post.html'

    def get_success_url(self):
        return reverse('posts:post_detail', args=[self.kwargs['post_id']])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_edit"] = True
        return context


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = None

    def get_success_url(self):
        username = (
            get_object_or_404(Post, pk=self.kwargs['post_id'])
            .author.username
        )
        return reverse('posts:profile', args=[username])

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        if self.object.author == self.request.user:
            self.object.delete()
        return HttpResponseRedirect(success_url)

    def get(self, request, post_id):
        return HttpResponseRedirect(reverse(
            'posts:post_detail',
            args=[post_id])
        )


class CommentCreate(LoginRequiredMixin, CreateView):
    template_name = 'posts/post_detail.html'
    form_class = CommentForm
    pk_url_kwarg = 'post_id'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.post = get_object_or_404(Post, pk=self.kwargs['post_id'])
        self.object.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.add_message(
            self.request,
            messages.WARNING,
            *form.errors.values())
        return redirect('posts:post_detail', self.kwargs['post_id'])


class FollowIndex(LoginRequiredMixin, ListView):
    template_name = 'posts/follow.html'
    paginate_by = COUNT_PAGINATOR_PAGE

    def get_queryset(self):
        posts = Post.objects.filter(
            author__following__user=self.request.user
        )
        return posts


class ProfileFollow(LoginRequiredMixin, UpdateView):
    def get(self, request, username):
        author = get_object_or_404(User, username=username)
        follow_create = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
        if not follow_create and author != request.user:
            Follow.objects.create(user=request.user, author=author)
        return HttpResponseRedirect(reverse('posts:follow_index'))


class ProfileUnfollow(LoginRequiredMixin, UpdateView):
    def get(self, request, username):
        author = get_object_or_404(User, username=username)
        follow_delet = get_object_or_404(
            Follow,
            user=request.user, author=author
        )
        if follow_delet:
            follow_delet.delete()
        return HttpResponseRedirect(reverse('posts:follow_index'))

yatube/templates/posts/create_post.html
<!-- templates/posts/create_post.html -->
{% extends "base.html" %}

{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
          <div class="card-body">

            {% include 'includes/view_errors.html' %}

            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}

              {% include 'includes/view_form.html' %}

              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Добавить
                  {% else %}
                    Сохранить
                  {% endif %} 
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %} 

{% block title %}Посты подписок{% endblock %}

{% block content %}
  <h1>Посты подписок</h1>
  {% include 'posts/includes/switcher.html' %}
  {% if page_obj %}
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
        
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  {% else %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <p class="text-center"><b>У вас нет подписок на авторов</b></p>
    </div> <!-- col -->
  </div> <!-- row -->
  {% endif %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ page_obj.0.group.title|title }}{% endblock %}

{% block content %}
  <h1>{{ page_obj.0.group.title }}</h1>
  <p>{{ page_obj.0.group.description }}</p>
  
  {% for post in page_obj %}
    {% include 'posts/includes/post_list.html' %}
      
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %} 
{% load cache %}

{% block title %}Последние обновления на сайте{% endblock %}

{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% include 'posts/includes/switcher.html' %}
  {% cache 20 index_page %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Пост {{ post.text|truncatechars:30 }}.{% endblock %}

{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
  
        <li class="list-group-item">
          {% if post.group.slug %}
            Группа: <b>{{ post.group.slug }}</b>
            <br>
            <a 
              href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
            </a>
          {% else %}
          Группа: отсутсвует
          {% endif %}
        </li>
        <li class="list-group-item">
          Автор: <b>{{ post.author.get_full_name }}</b>
          <br>
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span>{{ post.author.posts.count }}</span>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
    {% if user == post.author %}
      <a 
        class="btn btn-primary" 
        href="{% url "posts:post_edit" post.id %}"
      >
        редактировать запись
      </a>

      <!-- Button trigger modal -->
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
        удалить пост
      </button>
      <!-- Button trigger modal -->

    {% endif %}

    <!-- добавление коментариев -->
    {% include 'includes/add_comment.html' %}

    <!-- отображение комментариев  -->
    {% include 'includes/view_comment.html' %}

  </article>
</div>

<!-- Modal -->
{% include 'posts/includes/modal_delete.html' %}

{% endblock %}

{% include 'includes/footer.html' %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Профайл пользователя {{ author.get_full_name|title }}.{% endblock %}

{% block content %}    
  <h1>Все посты пользователя {{ author.get_full_name|title }}</h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
  {% if user.is_authenticated and user.username !=  author.username %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
  {% endif %}  
  {% for post in page_obj %}
    {% include 'posts/includes/post_list.html' %}
      
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}

{% include 'includes/footer.html' %}